image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/
    - packages/core/hc_asytrip/build/
    - packages/core/hc_bytecode/build/
    - packages/core/hc_grammar/build/
    - packages/core/hc_root/build/
    - packages/core/hc_tools/build/
    - packages/rt_typescript/build/

install_dependencies:
  stage: build
  script:
    - npm config set registry http://192.168.18.12:49155
    - npm install --no-audit
    - npm install typescript
    - npx tsc -p ./packages/core/hc_asytrip/tsconfig.json || true
    - npx tsc -p ./packages/core/hc_bytecode/tsconfig.json || true
    - npx tsc -p ./packages/core/hc_grammar/tsconfig.json || true
    - npx tsc -p ./packages/core/hc_root/tsconfig.json || true
    - npx tsc -p ./packages/core/hc_tools/tsconfig.json || true
    - npx tsc -p ./packages/rt_typescript/tsconfig.json || true

  artifacts:
    paths:
      - node_modules/
      - packages/core/hc_asytrip/build/
      - packages/core/hc_bytecode/build/
      - packages/core/hc_grammar/build/
      - packages/core/hc_root/build/
      - packages/core/hc_tools/build/
      - packages/rt_typescript/build/

version_ts_modules:
  stage: test
  script: npm run version_ts_packages
