[package]
name = "candlelib_hydrocarbon_wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/wasm_entry.rs"

[dependencies]
js-sys = "0.3.52"
wasm-bindgen = "0.2.75"

[profile.dev]
debug = 2