[package]
name = "hctoolkit_runtime"
version = "0.1.0"
edition = "2018"

[lib]
path = "source/lib.rs"

[dependencies]
coz = "0.1"
bumpalo = "3.8.0"

[profile.dev]
debug = 2

[profile.release]
opt-level=3
