[workspace]
members = ["./core", "./sandbox"]

[profile.dev]
debug = 2

[profile.release]
opt-level=3
debug =0
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false
lto = true
codegen-units=16
panic = "abort"